### ISSUE TITLE
autoconf errors

### ISSUE THREAD

**Issue by gdm85** [mcuelenaere/fsv#13]
By running `autoconf` I get:
```
configure.in:3: error: possibly undefined macro: AM_CONFIG_HEADER
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.in:10: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.in:51: error: possibly undefined macro: AM_CONDITIONAL
configure.in:63: error: possibly undefined macro: AM_GNU_GETTEXT
```

This is a known issue as one can figure out by googling around. The `configure` script is anyway generated but **not** usable:
```
./configure: line 2215: syntax error near unexpected token `config.h'
./configure: line 2215: `AM_CONFIG_HEADER(config.h)'
```

**Comment by Happy-Ferret** [comment]
Any reason you're using autoconf separately, over the autogen.sh provided with the project?

**Comment by gdm85** [comment]
Sorry, this is bogus. For some reason I hadn't found `autogen.sh`.

**Comment by Happy-Ferret** [comment]
I figured. 
It's relatively new to me, as well. Really great tool though. Don't know why there are still autotools projects without it.  :heart_eyes_cat:
