### ISSUE TITLE
Flickering in VirtualBox Arch

### ISSUE THREAD

**Issue by maxphillipsdev** [mcuelenaere/fsv#14]
I am experiencing a visibility flickering effect of the main 3D view whenever it is not animating a transition. The outlines will display however the actual boxes and their textures/text will not unless it is animating a transition. I am running this in VirtualBox on Arch Linux under the Ratpoison WM/XOrg. Thanks!

**Comment by ctrlcctrlv** [comment]
I have the same issue in i3. It is probably not easily fixable by the developer, though, as it works fine on real hardware. VirtualBox's 3D acceleration is really only good for basic compositor effects, simple games, some WebGL stuff and YouTube.

**Comment by Dmole** [comment]
https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1724810
