### ISSUE TITLE
Missing dependency: libglu

### ISSUE THREAD

**Issue by gdm85** [mcuelenaere/fsv#7]
Your configure is not picking up the dependency with libglu:

```
fatal error: GL/glu.h: No such file or directory
```

**Comment by Happy-Ferret** [comment]
I'm a bit late to the party, but as I recently ran into the exact same problem, I can tell you that this is due to a flawed apt-get line. 

There is no ```gtkgl-2.0-dev```. It's libgtkgl2.0-dev.

**Comment by gdm85** [comment]
@Happy-Ferret shouldn't configure fail with an error when `GL/glu.h` is not available?

**Comment by Happy-Ferret** [comment]
I'm no expert when it comes to C, but I think you might have a point there. Gonna see whether I can come up with a patch.

**Comment by gdm85** [comment]
@Happy-Ferret thanks, that would be nice. I think it should be as easy as copying the relevant `configure` segment from a similar project that does it right, however I am not either an automake/configure expert...

**Comment by Happy-Ferret** [comment]
After spending an evening trying to figure out those bloody m4 macros (it would, IMHO, be very nice to modularise configure), I ended up doing it the "old" way with AC_CHECK_HEADER(GL/glu.h). 

It's ten minutes to 1 AM at my place, so I'm not going to update my fork or even begin a pull request just yet, but just a heads-up that it's definitely making progress.

**Comment by gdm85** [comment]
Well, great achievement! I am not an m4 expert either, I prefer CMAKE these days..

**Comment by Happy-Ferret** [comment]
The attached pull request should solve the problem for good.

**Comment by mcuelenaere** [comment]
Should be fixed with 054f1482f4ab49cba166598164ee6d0cfe24b7a5

**Comment by gdm85** [comment]
Thanks!
